-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'WORKSPACE_MEMBER_REMOVED';
ALTER TYPE "NotificationType" ADD VALUE 'WORKSPACE_ROLE_UPDATED';
ALTER TYPE "NotificationType" ADD VALUE 'PROJECT_DELETED';
ALTER TYPE "NotificationType" ADD VALUE 'PROJECT_MEMBER_ADDED';